apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: game
        image: mamillapalli/tomven
        ports:
        - containerPort: 8080
